update `c_amc_data`.`t_data_permissions_module` set sort = '602' where business_type = 'style_pricing';

INSERT INTO `c_amc_data`.`t_data_permissions_module` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `function_module`, `function_module_code`, `business_name`, `business_type`, `server_name`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', '核价管理', 'pricing', '核价模板', 'pricingTemplate', '', 601);
INSERT INTO `c_amc_data`.`t_data_permissions_field` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `business_type`, `field_remarks`, `field_name`, `field_value_source`, `field_source_default_value`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', 'pricingTemplate', '品牌', 'brand', 'dict', 'C8_Brand', 0);
INSERT INTO `c_amc_data`.`t_data_permissions_field` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `business_type`, `field_remarks`, `field_name`, `field_value_source`, `field_source_default_value`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', 'pricingTemplate', '生产类型', 'devt_type', 'dict', 'DevtType', 1);

ALTER TABLE `s_pdm_data`.t_pricing_template add column brand varchar(50) not null default '5' comment '品牌';
ALTER TABLE `s_pdm_data`.t_pricing_template add column brand_name varchar(50) not null default 'MM' comment '品牌名称';
insert into `s_pdm_data`.t_pricing_template select MD5(UUID()) as id, template_code, template_name, default_flag, status, devt_type, devt_type_name, remarks, create_id, create_name, create_date, update_id, update_name, update_date, '0' as del_flag, company_code, '4' as brand, 'PM' as brand_name from `s_pdm_data`.t_pricing_template where del_flag = '0'

ALTER TABLE `s_pdm_data`.t_pricing add column devt_type varchar(50) default null comment '生产类型';
ALTER TABLE `s_pdm_data`.t_pricing add column devt_type_name varchar(50) default null comment '生产类型名称';

INSERT INTO `c_amc_data`.`t_data_permissions_field` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `business_type`, `field_remarks`, `field_name`, `field_value_source`, `field_source_default_value`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', 'hangTagList', '设计部', 'receive_dept_id', 'virtual_dept','', 0);

update `c_amc_data`.`t_data_permissions_module` set sort = '701' where business_type = 'hangTagList';

INSERT INTO `c_amc_data`.`t_data_permissions_module` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `function_module`, `function_module_code`, `business_name`, `business_type`, `server_name`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', '吊牌管理', 'hangTag', '多语言列表', 'styleCountryStatus', '', 702);
INSERT INTO `c_amc_data`.`t_data_permissions_field` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `business_type`, `field_remarks`, `field_name`, `field_value_source`, `field_source_default_value`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', 'styleCountryStatus', '品牌', 'brand', 'dict', 'C8_Brand', 0);
INSERT INTO `c_amc_data`.`t_data_permissions_field` (`id`, `company_code`, `create_id`, `create_name`, `create_date`, `update_id`, `update_name`, `update_date`, `remarks`, `del_flag`, `business_type`, `field_remarks`, `field_name`, `field_value_source`, `field_source_default_value`, `sort`) VALUES (MD5(UUID()), '677447590605750272', '77935446692619878','孔祥基', NOW(), '77935446692619878','孔祥基', NOW(), NULL, '0', 'styleCountryStatus', '设计部', 'receive_dept_id', 'virtual_dept', '', 1);