SELECT tpm.id                                                                             AS 打版任务id,
       MAX(IF(tns.node = '打版任务' AND tns.status = '打版完成', tns.end_date, NULL))     AS 纸样完成时间,
       MAX(IF(tns.node = '样衣任务' AND tns.status = '裁剪开始', tns.start_date, NULL))   AS 裁剪开始时间,
       MAX(IF(tns.node = '样衣任务' AND tns.status = '裁剪完成', tns.end_date, NULL))     AS 裁剪完成时间,
       MAX(IF(tns.node = '样衣任务' AND tns.status = '车缝完成', tns.end_date, NULL))     AS 样衣实际完成日期,
       MAX(IF(tns.node = '样衣任务' AND tns.status = '车缝进行中', tns.start_date, NULL)) AS 车缝开始日期,
       MAX(IF(tns.node = '样衣任务' AND tns.status = '车缝完成', tns.end_date, NULL))     AS 车缝完成日期,
       MAX(IF(tns.node = '样衣任务' AND tns.status = '物料齐套', tns.end_date, NULL))     AS 面辅料齐套,
       ts.style_name                                                                      as 款式样品,
       IF(ts.enable_flag = '1', '启用', '停用')                                           as 状态,
       ts.design_no                                                                       as 产品,
       ts.id                                                                              as StyleURL,
       tpm.sgl_kitting_date                                                               as 齐套日期,
       tpm.requirement_num                                                                as 打样需求数量,
       tpm.pattern_making_score                                                           as 版师工作量评分,
       tpm.color_name                                                                     as 采购的颜色,
       tpm.size                                                                           as 尺码,
       tpm.sample_type_name                                                               as 类型,
       tpm.cutter_name                                                                    as 裁剪师,
       tpm.pattern_making_quality_score                                                   as 版师质量评分,
       tpm.pattern_designer_name                                                          as 打样设计师,
       tpm.pattern_designer_id                                                            as 打样设计师Id,
       tpm.demand_finish_date                                                             as 样衣需求完成日期,
       tpm.sample_making_score                                                            as 样衣工工作量评分,
       tpm.pattern_making_quality_score                                                   as 样衣工质量评分,
       tpm.revision_reason                                                                as 改版原因,
       tpm.revision_comments                                                              as 改版意见,
       tpm.sample_bar_code                                                                as 样衣条码,
       tpm.pattern_no                                                                     as 样板号,
       tpm.sample_bar_code                                                                as 样品条码,
       tpm.pat_diff_name                                                                  as 打版难度,
       tpm.pat_seq_name                                                                   as 打样顺序,
       tpm.pattern_req_date                                                               as 纸样需求完成日期,
       tpm.pattern_room                                                                   as 产品供应商,
       tpm.pattern_room_id                                                                as 供应商编码,
       tpm.create_date                                                                    as 创建时间,
       tpm.create_name                                                                    as 创建人,
       tpm.update_name                                                                    as 修改人,
       tpm.requirement_num                                                                as 样衣完成数量,
       if('初版样' = tpm.sample_type_name, tpm.prm_send_date, tpm.design_send_date)       as 下发版师时间（指令）,
       if('0' = tpm.sample_complete_flag, '等待下发', '已发')                             as 下发给版师状态,
       tpm.demand_finish_date                                                             as 下发样衣组长时间（指令）,
       if('0' = tpm.pattern_no, '等待下发', '已发')                                       as 下发给打版组长状态,
       tpm.requirement_num                                                                as 需求数量（样衣指令）,
       tpm.stitcher                                                                       as 样衣师,
       tpm.pattern_finish_num                                                             as 纸样完成件数,
       if('1' = tpm.break_off_pattern, '中断', '正常')                                    as 延迟打板原因,
       null                                                                               as 放码日期,
       null                                                                               as 放码师,
       null                                                                               as 工艺单完成日期,
       null                                                                               as 后技术备注说明,
       null                                                                               as 面辅料信息,
       null                                                                               as 前技术确认是否齐套,
       null                                                                               as 样衣完成,
       null                                                                               as 技术收到日期,
       null                                                                               as 收到正确样日期,
       null                                                                               as 查版日期,
       null                                                                               as 面料检测单日期,
       GREATEST(tpm.update_date, ts.update_date, tns.update_date)                         as 修改时间,
       ts.historical_data                                                                               as 历史数据,
       if(tpm.del_flag = '0', '存在', '删除')                                             as 删除标识
FROM t_pattern_making tpm
         LEFT JOIN t_style ts ON ts.id = tpm.style_id AND ts.del_flag = '0'
         LEFT JOIN t_node_status tns ON tns.data_id = tpm.id AND tns.del_flag = '0'
GROUP BY tpm.id
UNION ALL
SELECT tppst.id                                                                               AS 打版任务id,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '打版完成', tns.end_date, NULL))     AS 纸样完成时间,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '裁剪开始', tns.start_date, NULL))   AS 裁剪开始时间,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '裁剪完成', tns.end_date, NULL))     AS 裁剪完成时间,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '车缝完成', tns.end_date, NULL))     AS 样衣实际完成日期,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '车缝进行中', tns.start_date, NULL)) AS 车缝开始日期,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '车缝完成', tns.end_date, NULL))     AS 车缝完成日期,
       MAX(IF(tns.node = '产前样衣任务' AND tns.status = '物料齐套', tns.end_date, NULL))     AS 面辅料齐套,
       ts.style_name                                                                          as 款式样品,
       IF(tppst.enable_flag = '1', '启用', '停用')                                            as 状态,
       ts.design_no                                                                           as 产品,
       ts.id                                                                                  as StyleURL,
       tppst.kitting_time                                                                     as 齐套日期,
       tppst.requirement_num                                                                  as 打样需求数量,
       null                                                                                   as 版师工作量评分,
       null                                                                                   as 采购的颜色,
       null                                                                                   as 尺码,
       '产前样'                                                                               as 类型,
       tppst.cutter_name                                                                      as 裁剪师,
       null                                                                                   as 版师质量评分,
       null                                                                                   as 打样设计师,
       null                                                                                   as 打样设计师Id,
       null                                                                                   as 样衣需求完成日期,
       tppst.sample_making_score                                                              as 样衣工工作量评分,
       tppst.sample_quality_score                                                             as 样衣工质量评分,
       null                                                                                   as 改版原因,
       null                                                                                   as 改版意见,
       tppst.sample_bar_code                                                                  as 样衣条码,
       tppst.code                                                                             as 样板号,
       tppst.sample_bar_code                                                                  as 样品条码,
       null                                                                                   as 打版难度,
       tppst.pat_seq                                                                          as 打样顺序,
       null                                                                                   as 纸样需求完成日期,
       tppst.pattern_room                                                                     as 产品供应商,
       tppst.pattern_room_id                                                                  as 供应商编码,
       tppst.create_date                                                                      as 创建时间,
       tppst.create_name                                                                      as 创建人,
       tppst.update_name                                                                      as 修改人,
       tppst.requirement_num                                                                  as 样衣完成数量,
       null                                                                                   as 下发版师时间（指令）,
       null                                                                                   as 下发给版师状态,
       null                                                                                   as 下发样衣组长时间（指令）,
       null                                                                                   as 下发给打版组长状态,
       tppst.requirement_num                                                                  as 需求数量（样衣指令）,
       tppst.stitcher                                                                         as 样衣师,
       null                                                                                   as 纸样完成件数,
       null                                                                                   as 延迟打板原因,
       tppst.grading_date                                                                     as 放码日期,
       tppst.grading_name                                                                     as 放码师,
       tppst.process_completion_date                                                          as 工艺单完成日期,
       tppst.tech_remarks                                                                     as 后技术备注说明,
       tppst.material_info                                                                    as 面辅料信息,
       if('1' = tppst.kitting, '是', '否')                                                    as 前技术确认是否齐套,
       if('1' = tppst.sample_complete_flag, '是', '否')                                       as 样衣完成,
       tppst.tech_receive_date                                                                as 技术收到日期,
       tppst.tech_receive_date                                                                as 收到正确样日期,
       tppst.sample_cha_ban_data                                                              as 查版日期,
       tppst.material_check_date                                                              as 面料检测单日期,
       GREATEST(tppst.update_date, ts.update_date, tns.update_date)                           as 修改时间,
       ts.historical_data                                                                               as 历史数据,
       if(tppst.del_flag = '0', '存在', '删除')                                               as 删除标识
FROM t_pre_production_sample_task tppst
         LEFT JOIN t_style ts ON ts.id = tppst.style_id AND ts.del_flag = '0'
         LEFT JOIN t_node_status tns ON tns.data_id = tppst.id AND tns.del_flag = '0'
GROUP BY tppst.id;
